### ISSUE TITLE
Unicode Normalization not appropriate for ASCII-8BIT

### ISSUE THREAD

**Issue by no5ugar** [X140Yu/debug_cocoapods_plugins_in_vscode#7]
![image](https://user-images.githubusercontent.com/16421062/128178160-e78073d0-191a-43b0-ab2e-94c73eaaa0ac.png)

使用 bundler debug。
cocoapods 是直接 clone master 分支。

是否与 cocoapods 版本有关，系统好像是 2.6.3，但看堆栈信息是 2.6.0 下的

**Comment by ttop2f** [comment]
![image](https://user-images.githubusercontent.com/16421062/128178850-9a4504df-a475-4e85-b427-1df11b652bb3.png)

发现我的设备单独安装 debase 是无法安装成功的

**Comment by no5ugar** [comment]
换了 release 的 cocoapods 版本就可以了~
